version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["node", "server.js"] # adapte si ton fichier d'entrée est différent
