name: Feature Request
description: Template for submitting feature requests.
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        ## Title
        A short title for the feature request.

  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the requested feature.
      placeholder: "Explain what the feature is about."

  - type: textarea
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: "Describe why this feature is important."

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information or context for the feature.
      placeholder: "Provide any other information if necessary."
