name: Backend CI

on:
  pull_request:
    branches: [stagging]
  push: 
    branches: [main, prod]
  
permissions:
  contents: read
  id-token: write  # Nécessaire pour l'authentification GCP avec Workload Identity

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Basic build check
        run: echo "✅ Basic build passed"

  call_lint:
    needs: build
    uses: ./.github/workflows/backend_lint.yml

  call_unit_tests:
    needs: call_lint
    uses: ./.github/workflows/backend_unit.yml

  call_integration_tests:
    needs: call_unit_tests
    uses: ./.github/workflows/backend_integration.yml

  call_e2e_tests:
    needs: call_integration_tests
    uses: ./.github/workflows/backend_e2e.yml
