name: Backend E2E Tests

on:
  workflow_call:
    inputs:
      trigger_source:
        required: true
        type: string

jobs:
  e2e-tests:
    if: ${{ github.event.inputs.trigger_source == 'Backend Integration Tests' }}
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run test:e2e

      - name: End to End test passed
        run: echo "✅ End to End tests passed"

  call_backend_deploy:
    needs: e2e-tests
    uses: ./.github/workflows/backend_deploy.yml
    with:
      trigger_source: 'Backend E2E Tests'
