name: Backend Integration Tests

on:
  workflow_run:
    workflows: ["Backend Unit Tests"]
    types:
      - completed

jobs:
  integration-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test:integration

      - name: Integration test passed
        run: echo "✅ Integration tests passed"
