name: Backend Lint

on:
  workflow_call:
    inputs:
      trigger_source:
        required: true
        type: string

jobs:
  lint:
    if: ${{ github.event.inputs.trigger_source == 'Backend CI' }}
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
