name: Backend Integration Tests

on:
  workflow_call:  # Utilisation de workflow_call pour être appelé par un autre workflow

permissions:
  contents: read
  id-token: write # Nécessaire pour l'authentification GCP avec Workload Identity
  
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install

      - name: Start backend server
        run: npm run start &

      - name: Run integration tests
        run: npm run test:integration
