name: Backend Unit Tests

on:
  workflow_call:
    inputs:
      trigger_source:
        required: true
        type: string

jobs:
  unit-tests:
    if: ${{ github.event.inputs.trigger_source == 'Backend Lint' }}
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Unit test passed
        run: echo "✅ Unit tests passed"
