name: Backend Deployment

on:
  push:
    branches:
      - prod # Le pipeline se déclenche lorsqu'il y a un push sur la branche prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.app-url }} # URL du déploiement (si nécessaire)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run build (if needed)
        run: npm run build # Si tu as un script de build dans ton package.json

      - name: Deploy to Production Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Utilisation de la clé SSH pour se connecter au serveur
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY username@your-production-server "cd /path/to/your/app && git pull origin prod && npm install && pm2 restart app"
        # Remplace les valeurs ci-dessus par les informations de ton serveur
        # Cette commande suppose que tu utilises PM2 pour gérer ton application
