name: Backend Format Check

on:
  workflow_call: # This workflow is called by the backend CI workflow

jobs:
  check-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run format check
        run: npx eslint . --max-warnings=0
        # --max-warnings=0 ensures that the job fails if there are any warnings
